services:

  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.compose
    ports:
      - "${PORT}:${PORT}"
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  db_service:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - .env.compose
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
volumes:
  timescaledb_data: